package org.jetbrains.tinygoplugin.services

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

private const val NO_ERROR_TINYGO_OUTPUT = """
        [GOROOT=/path/to/go/go1.16.7 #gosetup
        , GOPATH=/path/to/go #gosetup
        , tinygo info -target arduino -scheduler none -gc conservative #gosetup
        , TinyGo is a Go compiler for small places.
        , version: 0.16.0
        , usage: tinygo command [-printir] [-target=<target>] -o <output> <input>
    """

private fun prepareUnsupportedVersionTestInput(current: String, min: String, max: String) = """
        [GOROOT=/path/to/go/go1.16.7 #gosetup
        , GOPATH=/path/to/go #gosetup
        , tinygo info -target arduino -scheduler none -gc conservative #gosetup
        , requires go version $min through $max, got go$current
        , TinyGo is a Go compiler for small places.
        , version: 0.16.0
        , usage: tinygo command [-printir] [-target=<target>] -o <output> <input>
    """

private const val COULD_NOT_READ_GO_VERSION_ERROR_OUTPUT: String = """
        [GOROOT=/path/to/go/go1.17.5 #gosetup
        , GOPATH=/path/to/go #gosetup
        , tinygo info -target arduino -scheduler none -gc conservative #gosetup
        , could not read version from GOROOT (/path/to/go/go1.17.5): Invalid go version output:
        , // Code generated by go tool dist; DO NOT EDIT.

        , package sys

        , const StackGuardMultiplierDefault = 1

        , TinyGo is a Go compiler for small places.
        , version: 0.19.0
        , usage: tinygo command [-printir] [-target=<target>] -o <output> <input>
"""

internal class ErrorRegexUtilKtTest {
    @Test
    fun testNoErrorProvided() {
        val computedVersionTriple = extractIncompatibleVersionsError(NO_ERROR_TINYGO_OUTPUT)
        val couldNotReadGoVersionFound = extractCouldNotReadGoVersionError(NO_ERROR_TINYGO_OUTPUT)

        assertNull(computedVersionTriple)
        assertFalse(couldNotReadGoVersionFound)
    }

    private fun doSupportedVersionRangeExtractionTest(current: String, min: String, max: String) {
        val wantedVersionsTriple = Triple(current, min, max)
        val testInput = prepareUnsupportedVersionTestInput(current, min, max)
        val computedVersionTriple = extractIncompatibleVersionsError(testInput)
        val couldNotReadGoVersionFound = extractCouldNotReadGoVersionError(testInput)

        assertNotNull(computedVersionTriple)
        assertEquals(computedVersionTriple, wantedVersionsTriple)
        assertFalse(couldNotReadGoVersionFound)
    }

    @Test
    fun testTwoDigitMinorVerGoVersionExtraction() {
        doSupportedVersionRangeExtractionTest("1.16", "1.11", "1.15")
    }

    @Test
    fun testOneDigitMinorVerGoVersionExtraction() {
        doSupportedVersionRangeExtractionTest("1.6", "1.8", "1.9")
    }

    @Test
    fun testCouldNotReadGoVersionFound() {
        val computedVersionTriple = extractIncompatibleVersionsError(COULD_NOT_READ_GO_VERSION_ERROR_OUTPUT)
        val couldNotReadGoVersionFound = extractCouldNotReadGoVersionError(COULD_NOT_READ_GO_VERSION_ERROR_OUTPUT)

        assertNull(computedVersionTriple)
        assertTrue(couldNotReadGoVersionFound)
    }
}
